### ISSUE TITLE
:wave: animation

### ISSUE THREAD

**Issue by MaheshDetox** [Anirban166/Anirban166#2]
how about replacing the static 👋 emoji with an animation such as 
![wave](https://user-images.githubusercontent.com/56725675/98434506-52e95880-20f6-11eb-9094-9b2480d71173.gif)

**Comment by Anirban166** [comment]
Lgtm, gonna push 👍 
Arigato!

**Comment by MaheshDetox** [comment]
Dunno if issue links stay on forever though, hope it suffices to be permanent 😄

**Comment by Anirban166** [comment]
> Dunno if issue links stay on forever though, hope it suffices to be permanent 😄

They are indefinite for the moment, even if you didn't include the image/GIF in your comment post-upload (generated data with the corresponding link prevails as github user content, although that seems like a bad practice). I found an [alt](https://media.giphy.com/media/hvRJCLFzcasrR4ia7z/giphy.gif) as well, so cheers ✌️

**Comment by Anirban166** [comment]
They are indefinite for the moment, and would work even if you didn't include the .gif in your comment post-upload (uploaded data with it's correspondingly generated link lingers as Github user content, although that seems like a bad practice). I found an [alt](https://media.giphy.com/media/hvRJCLFzcasrR4ia7z/giphy.gif) as well (not residing on Github's servers), so cheers ✌️

**Comment by MaheshDetox** [comment]
Awesome!! I didn't knew that we could do without posting them, nice to know :)

**Comment by Anirban166** [comment]
Seems like the height constraint isn't being automatically set (probably an update dismissing that was made to be effective as of 06/01/22, as I noticed this since today) for a specified width (i.e., making both equal to be a square-sized image/gif), or vice versa. Gonna explicitly specify it for both now.

Setting a percentage isn't ideal. For instance, 5% of the device width looks good enough for larger screens, but for mobiles or devices with lower width resolution (or with skyscraper/portrait/vertical-dominant screen sizes), it looks too small and odd. And I can't write media queries for specific dimensions, given that markdown doesn't support CSS :)
